vich_uploader:
  db_driver: orm

  mappings:
    items:
      uri_prefix: /images/items
      upload_destination: "%kernel.project_dir%/public/images/items"
      namer: Vich\UploaderBundle\Naming\OrignameNamer
