controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation
gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
